name: CI

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  build-test:
    name: Build & Test
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Ahorcado.sln'
      
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: |
        dotnet clean ${{ env.SOLUTION }}
        dotnet restore ${{ env.SOLUTION }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION }} --configuration ${{ env.BUILD_CONFIG }}

    - name: Test
      run: dotnet test ${{ env.SOLUTION }} --configuration ${{ env.BUILD_CONFIG }}
