name: codecoverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
        
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
             
      - name: Run tests and collect coverage
        run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults

      - name: Generate coverage report
        run: |
          reportgenerator -reports:"./TestResults/**/*.xml" -targetdir:"coverage-report" -reporttypes:HtmlInline_AzurePipelines

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage-report
