name: codecoverage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      - name: Install ChromeDriver
        uses: nanasess/setup-chromedriver@v1

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore
        
      - name: Start the application
        run: |
          dotnet run --project Ahorcado.MVC/AhorcadoMVC.csproj --urls "http://localhost:5000" &
          Start-Sleep -s 20 # Espera 20 segundos para que la aplicación se inicie completamente
        
      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool
             
      - name: Run tests and collect coverage
        run: dotnet test --no-build --collect:"XPlat Code Coverage" --results-directory ./TestResults
          
      - name: Generate coverage report
        run: |
          reportgenerator -reports:"./TestResults/**/*.xml" -targetdir:"coverage-report" -reporttypes:HtmlInline_AzurePipelines

      - name: Upload coverage report artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage-report

