name: deploye

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Start Web Server
      run: |
        dotnet publish -c Release -o ./publish
        dotnet ./publish/TP_Ahorcado.dll &
      working-directory: ./src
    - name: Test
      run: dotnet test --no-build
    - name: Publish
      run: dotnet publish --configuration Release --no-build --output published
    - name: Run Acceptance Tests
      run: |
        dotnet test AcceptanceTest/AcceptanceTest.csproj --configuration Release
    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: published
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: published
    - name: Deploy to Vercel
      uses: vercel-action@v1
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
