# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: deploy

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  AZURE_WEBAPP_NAME: "agilesv2"
  
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Publish the project
      run: dotnet publish ./Ahorcado.MVC/AhorcadoMVC.csproj --configuration Release --output ./publish
      
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./publish

    - name: emirdeliz-chromedriver
  # You may pin to the exact commit or the version.
  # uses: emirdeliz/emirdeliz-chromedriver@90fc00f5358fd7b4f44a6854d461c1969be4c31c
      uses: emirdeliz/emirdeliz-chromedriver@v0.0.6
      with:
        arch: win32

    - name: Start ChromeDriver
      run: |
        .\chromedriver\chromedriver.exe --allowed-ips=0.0.0.0/0 # Permitir conexiones desde cualquier IP, ajusta según sea necesario
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
